# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "1.16" ]
  pull_request:
    branches: [ "1.16" ]
  workflow_dispatch:

jobs:
  Test-And-Deploy:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
      COMMIT_AUTHOR: ${{ github.event.commits[0].author.name }}
      WEBHOOK_URL: ${{ secrets.PN_WEBHOOK }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Create Server EULA
        run: |
          mkdir run
          echo "eula=true" > run/eula.txt
#        - name: Dummy Run Server Until World Tick
#          run: ./gradlew runServer
      - name: Deploy Webhook
        run: ./gradlew postRequest -x :dumb_library:postRequest -x :dumb_library:javadoc -x javadoc
  Github-Webhook-If-Fail:
    needs: Test-And-Deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1.8.5
        env:
          DISCORD_WEBHOOK: ${{ secrets.PN_WEBHOOK }}
        with:
          status: failure
          nodetail: true
          title: Error In Job
          description: |
            [Build ${{ env.GITHUB_RUN_NUMBER }} has errored - ${{ github.event.commits[0].message }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Blame ${{ github.event.commits[0].author.name }}